//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anchorage.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anchorage.Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;RSAKeyValue&gt;&lt;Modulus&gt;0fXeHH/Em8mfMG2P9mXUbBE1lGptLjzJa7ZZLtHP5c7DP6FAYzbFNTJ79tIJUBL+PblCm/r3nTQE577lyoshiE6kKhNnlHu47PbjC1IvmaTiQ32lbJRjnXOSNcnNqsK3TsXmTfJuHVm5fS1OqJmQ3OgW1D0tgzq7FOmtTlbIp9U=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;2V82q/POYdKJuXPlBEy9rH9egJ5NUYZftjzMGSBGd1LL/HPOgVXG6pYzEfj32RVl56iU/34gkGell0MHdF09uw==&lt;/P&gt;&lt;Q&gt;90V8e1l0uMzyz0hZmo+m8Me+iuSI1OXzXP+Y5W7Uyfsod1/7lcEjbgncuj2JZ8X6cA2GmuunhzPYAxj6/7CPrw==&lt;/Q&gt;&lt;DP&gt;iQDD2pjt6SXjfCmZnJ4ppgEZNQORQ+LnjFrBYMzA3RAoVVNAQrAnkU9dnORIgmBEPEA6uNVr/Nf2vGGY3zStZQ==&lt; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RSAString {
            get {
                return ResourceManager.GetString("RSAString", resourceCulture);
            }
        }
    }
}
