// <auto-generated />
using System;
using Anchorage.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Anchorage.Server.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20181124134912_dafegewrghrethj")]
    partial class dafegewrghrethj
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Anchorage.Shared.Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BoardDefaultName")
                        .IsRequired();

                    b.Property<string>("BoardKey")
                        .IsRequired();

                    b.Property<string>("BoardName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Boards");

                    b.HasData(
                        new { Id = 1, BoardDefaultName = "以下、名無しにかわりまして裏VIP(´・ω・`)がお送りします", BoardKey = "news7vip", BoardName = "裏VIP" },
                        new { Id = 2, BoardDefaultName = "雑談うんちー", BoardKey = "coffeehouse", BoardName = "雑談ルノワール" }
                    );
                });

            modelBuilder.Entity("Anchorage.Shared.Models.Response", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author")
                        .IsRequired();

                    b.Property<string>("Body")
                        .IsRequired();

                    b.Property<DateTimeOffset>("Created");

                    b.Property<string>("HostAddress")
                        .IsRequired();

                    b.Property<string>("Mail");

                    b.Property<string>("Name");

                    b.Property<int>("ThreadId");

                    b.HasKey("Id");

                    b.ToTable("Responses");

                    b.HasData(
                        new { Id = 1, Author = "oienriboe", Body = "うんちぶりぶりのすばらしさはいじょうなものであるということ", Created = new DateTimeOffset(new DateTime(2018, 11, 24, 22, 49, 11, 775, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0)), HostAddress = "127.0.0.1", ThreadId = 1 },
                        new { Id = 2, Author = "gerg", Body = "やはりなというかんじである", Created = new DateTimeOffset(new DateTime(2018, 11, 24, 22, 49, 11, 775, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0)), HostAddress = "127.0.0.1", ThreadId = 1 },
                        new { Id = 3, Author = "fweg", Body = "それはいえどもわれわれのかんじるところではないな", Created = new DateTimeOffset(new DateTime(2018, 11, 24, 22, 49, 11, 775, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0)), HostAddress = "192.168.0.0.1", ThreadId = 2 },
                        new { Id = 4, Author = "oienriboe", Body = "ではやはりそうとであるか", Created = new DateTimeOffset(new DateTime(2018, 11, 24, 22, 49, 11, 775, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0)), HostAddress = "127.0.0.1", ThreadId = 2 },
                        new { Id = 5, Author = "gerg", Body = "なあなあでおわらせてはいけない", Created = new DateTimeOffset(new DateTime(2018, 11, 24, 22, 49, 11, 775, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0)), HostAddress = "114.51.41.91", ThreadId = 3 }
                    );
                });

            modelBuilder.Entity("Anchorage.Shared.Models.Thread", b =>
                {
                    b.Property<int>("ThreadId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author")
                        .IsRequired();

                    b.Property<string>("BoardKey")
                        .IsRequired();

                    b.Property<DateTimeOffset>("Created");

                    b.Property<long>("DatKey");

                    b.Property<DateTimeOffset>("Modified");

                    b.Property<int>("ResponseCount");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("ThreadId");

                    b.ToTable("Threads");

                    b.HasData(
                        new { ThreadId = 1, Author = "oienriboe", BoardKey = "news7vip", Created = new DateTimeOffset(new DateTime(2018, 11, 24, 22, 49, 11, 773, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0)), DatKey = 0L, Modified = new DateTimeOffset(new DateTime(2018, 11, 24, 22, 49, 11, 775, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0)), ResponseCount = 2, Title = "ええな" },
                        new { ThreadId = 2, Author = "fweg", BoardKey = "news7vip", Created = new DateTimeOffset(new DateTime(2018, 11, 24, 22, 49, 11, 775, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0)), DatKey = 0L, Modified = new DateTimeOffset(new DateTime(2018, 11, 24, 22, 49, 11, 775, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0)), ResponseCount = 2, Title = "ええぞ" },
                        new { ThreadId = 3, Author = "gerg", BoardKey = "coffeehouse", Created = new DateTimeOffset(new DateTime(2018, 11, 24, 22, 49, 11, 775, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0)), DatKey = 0L, Modified = new DateTimeOffset(new DateTime(2018, 11, 24, 22, 49, 11, 775, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0)), ResponseCount = 1, Title = "いいぞ" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
